before_script:
  - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
  - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
variables:
  APP_REPO_NAME: "react-demo"
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
stages:
  - Package
  - Deploy
package:
  stage: Package
  tags:
    - runner
  when: manual
  script:
    - git clone https://github.com/MiranaSGit/myReactApp.git
    - cd myReactApp
    - docker build --force-rm -t ${ECR_REGISTRY}/${APP_REPO_NAME} .
    # Build için Docker file githubtan nasıl çekilecek?
    #- aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
    - docker push ${ECR_REGISTRY}/${APP_REPO_NAME}

deploy:
  stage: Deploy
  when: manual
  tags:
    - runner
  script:
    - terraform apply -var "image=${ECR_REGISTRY}/${APP_REPO_NAME}" -auto-approve'

##############################################################################################

stages:
  - Build
  - Push to ECR
  - Deploy
build:
  stage: Build
  tags: 
    - runner
  when: manual
  script:
    - git clone https://github.com/MiranaSGit/myReactApp.git
    - cd myReactApp
    - docker build --force-rm -t 360800251837.dkr.ecr.us-east-1.amazonaws.com/react-demo .
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 360800251837.dkr.ecr.us-east-1.amazonaws.com

Push to ECR:
  stage: Push to ECR
  tags: 
    - runner
  script:
    - docker push 360800251837.dkr.ecr.us-east-1.amazonaws.com/react-demo

deploy:
  stage: Deploy
  tags:
    - runner
  script:
    - git clone https://github.com/MiranaSGit/myReactApp.git
    - cd myReactApp
    - terraform init
    - terraform apply -var "image=360800251837.dkr.ecr.us-east-1.amazonaws.com/react-demo" -auto-approve
